name: peterlogg-dotcom-backend
version: 0.1.0.0
github: "peterlogg/peterlogg-dotcom-backend"
license: BSD3
author: "Peter Logg"
maintainer: "loggpeter@gmail.com"
copyright: "2020 Peter Logg"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/peterlogg-dotcom-backend#readme>

dependencies:
  - base >= 4.7 && < 5
  - scotty
  - http-types
  - wai-cors

library:
  source-dirs: src

executables:
  peterlogg-dotcom-backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - peterlogg-dotcom-backend

tests:
  peterlogg-dotcom-backend-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - peterlogg-dotcom-backend
