name: Bump version + build + push image
on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE: peterlogg-dotcom-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.8.4' # Exact version of ghc to use
        enable-stack: true
        stack-version: 'latest'

    - name: Testing suite
      run: stack test

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

    # Build the Docker image
    - name: Build image
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
          .
    # Push the Docker image to Google Container Registry
    - name: Publish image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
