name: Build and check

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.4' # Exact version of ghc to use
          enable-stack: true
          stack-version: 'latest'
      - run: stack test
